import styles from "./layout.module.css";

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className={styles.header}>From layout</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
